services:
  api:
    build: .
    container_name: fastapi
    image: fastapi:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
